fun main() {
    val debitCard = DebitCard(15000.0)
    println("Пользуемся дебетовой картой:")
    debitCard.balanceInfo()
    debitCard.topUp(1000.0)
    debitCard.balanceInfo()
    println()

    val creditCard = CreditCard(5000.0, 10000.0)
    println("Пользуемся кредитной картой:")
    creditCard.availableFundsInfo()
    creditCard.pay(1200.0)
    creditCard.availableFundsInfo()
    creditCard.topUp(3000.0)
    creditCard.availableFundsInfo()
    creditCard.pay(12000.0)
    creditCard.availableFundsInfo()
    creditCard.topUp(500.0)
    creditCard.availableFundsInfo()
    creditCard.topUp(6000.0)
    creditCard.availableFundsInfo()
    println()

    val debitCardWithCashBack = DebitCardWithCashBack(10000.0)
    println("Пользуемся дебетовой картой с кэшбеком:")
    debitCardWithCashBack.availableFundsInfo()
    debitCardWithCashBack.pay(5000.0)
    debitCardWithCashBack.availableFundsInfo()
    debitCardWithCashBack.pay(4000.0)
    debitCardWithCashBack.availableFundsInfo()
    debitCardWithCashBack.pay(4000.0)
    debitCardWithCashBack.availableFundsInfo()
    println()

    val creditCardWithBonus = CreditCardWithBonus(5000.0, 10000.0)
    println("Пользуемся кредитной картой с бонусом:")
    creditCardWithBonus.availableFundsInfo()
    creditCardWithBonus.pay(2000.0)
    creditCardWithBonus.availableFundsInfo()
    creditCardWithBonus.pay(8000.0)
    creditCardWithBonus.availableFundsInfo()
}